const ITEMS = [
  { id: 1, name: "Laptop", price: 1000, availableQuantity: 10, image: "/general-product" },
  { id: 2, name: "Smartphone", price: 800, availableQuantity: 10, image: "/general-product" },
  { id: 3, name: "Headphones", price: 200, availableQuantity: 10, image: "/general-product" },
  { id: 4, name: "Smartwatch", price: 250, availableQuantity: 10, image: "/general-product" },
  { id: 5, name: "Tablet", price: 600, availableQuantity: 10, image: "/general-product" },
  { id: 6, name: "Keyboard", price: 50, availableQuantity: 10, image: "/general-product" },
  { id: 7, name: "Mouse", price: 30, availableQuantity: 10, image: "/general-product" },
  { id: 8, name: "Monitor", price: 300, availableQuantity: 10, image: "/general-product" },
  { id: 9, name: "Printer", price: 150, availableQuantity: 10, image: "/general-product" },
  { id: 10, name: "Desk Lamp", price: 40, availableQuantity: 10, image: "/general-product" },
  { id: 11, name: "Gaming Console", price: 500, availableQuantity: 10, image: "/general-product" },
  { id: 12, name: "External Hard Drive", price: 100, availableQuantity: 10, image: "/general-product" },
  { id: 13, name: "Router", price: 80, availableQuantity: 10, image: "/general-product" },
  { id: 14, name: "Webcam", price: 60, availableQuantity: 10, image: "/general-product" },
  { id: 15, name: "Bluetooth Speaker", price: 120, availableQuantity: 10, image: "/general-product" },
  { id: 16, name: "Portable Charger", price: 40, availableQuantity: 10, image: "/general-product" },
  { id: 17, name: "Projector", price: 400, availableQuantity: 10, image: "/general-product" },
  { id: 18, name: "Digital Camera", price: 700, availableQuantity: 10, image: "/general-product" },
  { id: 19, name: "Smart Home Hub", price: 150, availableQuantity: 10, image: "/general-product" },
  { id: 20, name: "VR Headset", price: 350, availableQuantity: 10, image: "/general-product" },
  { id: 21, name: "Electric Kettle", price: 70, availableQuantity: 10, image: "/general-product" },
  { id: 22, name: "Fitness Tracker", price: 90, availableQuantity: 10, image: "/general-product" },
  { id: 23, name: "Wireless Earbuds", price: 150, availableQuantity: 10, image: "/general-product" },
  { id: 24, name: "Electric Scooter", price: 800, availableQuantity: 10, image: "/general-product" },
  { id: 25, name: "Coffee Maker", price: 200, availableQuantity: 10, image: "/general-product" },
  { id: 26, name: "Air Purifier", price: 300, availableQuantity: 10, image: "/general-product" },
  { id: 27, name: "Smart Doorbell", price: 180, availableQuantity: 10, image: "/general-product" },
  { id: 28, name: "Streaming Stick", price: 50, availableQuantity: 10, image: "/general-product" },
  { id: 29, name: "Electric Toothbrush", price: 60, availableQuantity: 10, image: "/general-product" },
  { id: 30, name: "Smart Thermostat", price: 250, availableQuantity: 10, image: "/general-product" },
];

export default ITEMS;
